# Generated by Django 5.0 on 2024-02-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='nombre_producto',
        ),
        migrations.AddField(
            model_name='clientes',
            name='nombre_producto',
            field=models.ManyToManyField(blank=True, null=True, to='productos.productos'),
        ),
    ]
