# Generated by Django 5.0 on 2024-02-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_clientes_nombre_producto_and_more'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='nombre_producto',
            field=models.ManyToManyField(blank=True, to='productos.productos'),
        ),
    ]
