# Generated by Django 5.0 on 2024-02-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_clientes_nombre_producto_and_more'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='nombre_producto',
        ),
        migrations.AddField(
            model_name='clientes',
            name='nombre_producto',
            field=models.ManyToManyField(to='productos.productos'),
        ),
    ]
