# Generated by Django 5.0 on 2024-02-09 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generarPago', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generarpago',
            old_name='cedula',
            new_name='id_clientes',
        ),
    ]
