# Generated by Django 5.0 on 2024-02-09 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generarPago', '0002_rename_cedula_generarpago_id_clientes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generarpago',
            old_name='id_clientes',
            new_name='idClientes',
        ),
    ]
