# Generated by Django 5.0 on 2024-02-09 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generarPago', '0003_rename_id_clientes_generarpago_idclientes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generarpago',
            old_name='idClientes',
            new_name='cedula',
        ),
    ]
