# Generated by Django 5.0 on 2024-02-09 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generarPago', '0004_rename_idclientes_generarpago_cedula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generarpago',
            old_name='cedula',
            new_name='idCliente',
        ),
    ]
